### PR TITLE
Merge in advancements from KayZGames and make null safe

### PR DESCRIPTION
**Pull request by eseidel**
A whole bunch of commits from KayZGames.

I also updated the package to be null safe and made the test run with package:test.

### CODE REVIEW

**Comment by sethladd** [comment]
Thank you!

**Comment by sethladd** [comment]
If you would like, we can add your name to the contributors in the readme. What do you think?

**Comment by eseidel** [comment]
🤷   @denniskaselow and @Fox32 are the big contributors here.

**Comment by denniskaselow** [comment]
I'm fine either way.

**Pull request merged**
